spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: file:///D:/IDE_IDEA/Profundizacion- CES4/taller2-configData
  security:
    user:
      name: ${CONFIG_USER}
      password: ${CONFIG_PASSWORD}
server:
  port: 9000
